#all:
#    services:
#        logger:
#            class: MiguelAlcaino\Service\Logger

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        public: true

    MiguelAlcaino\:
        resource: '../src/*'
        exclude: '../src/{Action,DependencyInjection}'